name: denoised-env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # Core Python and PyTorch
  - python=3.11.5
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - mkl=2024.0.0
  
  # Scientific computing
  - numpy=1.26.0
  - pandas=2.1.1
  - scipy=1.11.2
  - scikit-learn=1.3.1
  - networkx=3.1
  - sympy=1.12
  
  # Data visualization
  - matplotlib=3.8.0
  - seaborn=0.12.2
  - plotly=5.17.0
  
  # Data processing
  - pyarrow=13.0.0
  - openpyxl=3.1.2
  - xlrd=2.0.1
  - feather-format=0.4.1
  - statsmodels=0.14.0
  
  # Jupyter and development tools
  - ipykernel=6.25.2
  - notebook=6.5.4
  - jupyterlab=3.6.5
  - nbconvert=6.5.3
  - ipywidgets=8.1.1
  - voila=0.4.3
  
  # Utilities
  - pip=23.2.1
  - requests=2.31.0
  - pyyaml=6.0.1
  - tqdm=4.66.1
  
  # Image processing and additional libraries
  - pillow=9.4.0
  - pip:
    - opencv-python==4.9.0.80
    - h5py==3.10.0
    - scikit-image==0.22.0
    - imageio==2.33.1
    - tifffile==2024.1.30
    - imagecodecs==2024.1.1
    - lazy-loader==0.3
